### ISSUE TITLE
No key to jump to next text filed in LicenseNumberActivity input fields [1-2hr]

### ISSUE THREAD

**Issue by tuancoltech** [elimu-ai/appstore#126]

**Comment by jo-elimuai** [comment]
Is this problem mostly relevant on small screens? @bvalbo Could you add a screenshot or some more information explaining this problem?

**Comment by bvalbo** [comment]
Just realized the "enter" key works as the "jump to next field" key. Guess I'm not too used to Android... So I guess you could remove this bug.
