### ISSUE TITLE
Hyphen (-) should show up automagically after input of 4 characters in License field [1-2hr]

### ISSUE THREAD

**Issue by tuancoltech** [elimu-ai/appstore#127]

**Comment by jo-elimuai** [comment]
@bvalbo @tuancoltech This is a very good feature to add, and would make things much easier for the user handling the tablets. However, let's wait for some time until we have a confirmation that the license number will actually be in the format `xxxx-xxxx-xxxx-xxxx`. 

We first need to update the back-end with this format restriction before we can implement this feature in the Appstore.

Related to https://github.com/elimu-ai/webapp/issues/498
