### ISSUE TITLE
Do not reset progressbars when returning to app after leaving it [8-16h]

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/appstore#128]
Bug reported by @bvalbo: 
> "I started downlod for all apps, but then screensaver kicked in, and when turned back on, I had to restart all. Is there anyway to make it continue downloading in the background?"

**Comment by jo-elimuai** [comment]
@tuancoltech The current download does continue in the background after leaving the app, right? Or is the AsyncTask cancelled when the app is closed?

**Comment by tuancoltech** [comment]
@jo-elimuai What do you mean by closing app? Is this pressing home key while inside the app, or pressing back key (The same with clearing app from recent task) ?

With the current logic, pressing home key while inside the app should not stop the download progress.
However pressing back key or clearing app from recent task will destroy everything, including progressing downloads.

**Comment by jo-elimuai** [comment]
@bvalbo When you say that you had to restart, do you mean that you had to restart the app itself? Or was the list of apps still present (without having to load them again) when you unlocked the screen?

**Comment by bvalbo** [comment]
This is quite a while ago, but I think the app was fine, it was just that I had to press the Download buttons to start downloading again.
